module Physics

import public Empirical.Comparison
import public Empirical.Measurements
import public Empirical.Ratio
import public Math.ActionPrinciple
import public Math.ApplicativeHomomorphism
import public Math.BlackHolePhaseTransition
import public Math.CavityQuantumElectrodynamics
import public Math.ChiralAnomaly
import public Math.ChromoLawFunctor
import public Math.ConstructiveBaryogenesis
import public Math.CosmicGenesis
import public Math.CosmologicalWaveEquation
import public Math.DegeneracyMassLimit
import public Math.DensityMatrix
import public Math.ElectromagneticEnergyFlow
import public Math.EntanglementAreaLaw
import public Math.EvaporationEntropyCurve
import public Math.FlavorMixing
import public Math.FluctuationTheorem
import public Math.FractionalQuantumHall
import public Math.GalacticRotationCurve
import public Math.GaugeSpinorCoupling
import public Math.GravitationalCollapseLimit
import public Math.GravitationalWaveDynamics
import public Math.HallViscosity
import public Math.HelmholtzFreeEnergy
import public Math.HolographicBound
import public Math.HolonomyPhase
import public Math.HorizonRadiation
import public Math.InformationErasureCost
import public Math.LatticeFluidTransport
import public Math.LawFunctor
import public Math.MacromolecularChirality
import public Math.Magnetohydrodynamics
import public Math.MultiTerminalConduction
import public Math.NeutrinoOscillation
import public Math.OscillatingReactions
import public Math.PeakBindingEnergy
import public Math.PhaseInvarianceMeasure
import public Math.PhysicsLaw
import public Math.PhysicsMonad
import public Math.PhysicsScaleTransforms
import public Math.PlasmaRecombination
import public Math.PrefixCodeOptimality
import public Math.QuantumPotential
import public Math.QuantumTeleportation
import public Math.RGDecimator
import public Math.RationalKepler
import public Math.RationalRefraction
import public Math.ReciprocalTransport
import public Math.RelativisticSpinor
import public Math.RenormalizationInformationFlow
import public Math.RetardedDipoleForce
import public Math.RotatingSpacetime
import public Math.StringTension
import public Math.SuperconductingFluxQuantization
import public Math.SuperconductingGap
import public Math.SymmetryBreakingMass
import public Math.ThermalDistribution
import public Math.TopologicalChernNumber
import public Math.TopologicalGaugeMass
import public Math.TopologicalInsulator
import public Math.ToricCode
import public Math.ToroidalAstrodynamics
import public Math.TripleAlphaNucleosynthesis
import public Math.VacuumDispersion
import public Math.VacuumPolarization
import public Math.WorkFreeEnergyEquality

%default total
